name: calo

on:
  #schedule:
    #- cron: '0 */3 * * *'  # Actualise toutes les 3 heures
  workflow_dispatch:       # Permet le déclenchement manuel

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Référentiel d’extraction
        uses: actions/checkout@v4

      - name: Créer un dossier fr
        run: mkdir -p fr


      - name: test de code
        run: |
          source=$(curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" https://hdfauth.ftven.fr/esi/TA?url=https://simulcast-p.ftven.fr/simulcast/France_2/hls_fr2/index.m3u8)
          base=$(curl -e "https://www.france.tv/" -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" "$source")
          echo "$base" > fr/fr2.m3u8
          #mu=$(echo $source | grep -oP "[^\n\r]*index")
          #sed -i "s|France|$mu|g" fr/fr2.m3u8
          #sed -i "s|index|France|g" fr/fr2.m3u8

          
      - name: Identifier l'adresse IP de github
        run: |
          github_ip=$(curl https://api.ipify.org)
          echo "L'adresse IP de github est: $github_ip" > githubip.data    

      - name: Valider et envoyer les modifications
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          ls -la 
          git commit -m "Dernière actualisation"
          git push
