name: calo

on:
  #schedule:
    #- cron: '0 */3 * * *'  # Actualise toutes les 3 heures
  workflow_dispatch:       # Permet le déclenchement manuel

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Référentiel d’extraction
        uses: actions/checkout@v4

      - name: Créer un dossier fr
        run: mkdir -p fr

      # https://fr.linux-console.net/?p=3665  https://linux.die.net/man/1/curl   
      # https://www.ionos.fr/digitalguide/serveur/configuration/commande-sed-de-linux/
      # tr > https://fr.linux-console.net/?p=30376

      # curl est un outil de transfert de données en ligne de commandes et terminal.
      # Il prend en charge les protocoles pris en charge (DICT, FILE, FTP, FTPS, GOPHER, HTTP, HTTPS, IMAP,
      # IMAPS, LDAP, LDAPS, POP3, POP3S, RTMP, RTSP, SCP, SFTP, SMB, SMBS, SMTP, SMTPS, TELNET et TFTP).

      # user-agent ou -A indique un agent utilisateur.
      # -s silencieux, pas de sortie.
      # -H Transmettre un en-tête personnalisé au serveur.
      # -o dans grep ne correspond qu’à - seule la chaîne correspondante sera affichée.
      # -P regex
      # -e URL de référence.
# echo tr -d 'http://s2.callofliberty.fr/HLS-AES/' > fr/videof5.m3u8


# | yq e '.url' # yq JSON est un sous-ensemble de YAML
# | fx .delivery.url
# | jshon -e url
# | getJsonVal "['delivery']['url'][0]"

      - name: Exécuter le script et générer M3U8 pour fr2
        run: |
          base=$(curl -s -H "User-Agent: ELinks/0.13.2 (textmode; Linux 5.15.0-27-generic x86_64; 80x15-2)" http://www.callofliberty.fr/tv/2-france.2/2-france.2.php | grep -oP "source:\s*'\K[^']+(?=',)")
          flux=$(curl -e "http://www.callofliberty.fr/" -A "ELinks/0.13.2 (textmode; Linux 5.15.0-27-generic x86_64; 80x15-2)" $base)
          echo "$flux" > fr/videof2.m3u8
          #  ("s/ /_/g") indique à sed de se comporter de façon globale ("récursive").
          # Vous devez échapper les caractères spéciaux avec \.
          # L’option pour mettre à jour le fichier en place est -i.
          sed -i 's/http:\/\/s2.callofliberty.fr\/HLS-AES\/https/https/g' fr/videof2.m3u8



      - name: Extraire les modifications de la télécommande
        run: git pull origin main          

      - name: Valider et envoyer les modifications
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          ls -la 
          git commit -m "Dernière actualisation"
          git push
