name: calo

on:
  schedule:
    - cron: '0 */3 * * *'  # Actualise toutes les 3 heures
  workflow_dispatch:      # Activer le déclenchement manuel

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Référentiel d’extraction
        uses: actions/checkout@v4

      - name: Créer un dossier fr
        run: mkdir -p fr

      - name: Créer un dossier txt
        run: mkdir -p txt        

      # https://www.petergirnus.com/blog/curl-command-line-ultimate-reference-guide   

      # curl est un outil de transfert de données en ligne de commandes et terminal.
      # Il prend en charge les protocoles pris en charge (DICT, FILE, FTP, FTPS, GOPHER, HTTP, HTTPS, IMAP,
      # IMAPS, LDAP, LDAPS, POP3, POP3S, RTMP, RTSP, SCP, SFTP, SMB, SMBS, SMTP, SMTPS, TELNET et TFTP).


      - name: Exécuter le script et générer M3U8 pour fr2
        run: |
          # user-agent ou -A indique un agent utilisateur.
          # -s silencieux, pas de sortie.
          # -H Transmettre un en-tête personnalisé au serveur.
          # -o dans grep ne correspond qu’à - seule la chaîne correspondante sera affichée.
          # -P regex
          # -e URL de référence.
          # curl_output=$ variable ? Mettez la sortie de curl dans une variable, et récupdrer cette variable avec $curl_output
          base=$(curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" http://www.callofliberty.fr/tv/2-france.2/2-france.2.php | grep -oP "source:\s*'\K[^']+(?=',)")
          flux=$(curl -e "http://www.callofliberty.fr/" -A "Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" $base)
          echo "$flux" > fr/videof2.m3u8  # Utiliser un > unique pour écraser le contenu existant   

# grep -rl 'windows' ./ | xargs sed -i 's/windows/linux/g'
# Cela recherchera la chaîne 'windows' dans tous les fichiers relatifs au répertoire courant et remplacera
# 'windows' par 'linux' pour chaque occurrence de la chaîne dans chaque fichier.



      - name: Run Script and Generate M3U8 for F3
        run: |
          curl_output=$(curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" http://www.callofliberty.fr/tv/3-france.3/3-france.3.php | grep -oP "source:\s*'\K[^']+(?=',)")
          curl_output2=$(curl -e "http://www.callofliberty.fr/" -A "Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" $curl_output)
          echo "$curl_output2" > fr/videof3.m3u8  # Use single > to overwrite existing content   

      - name: Run Script and Generate M3U8 for F4
        run: |
          curl_output=$(curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" http://www.callofliberty.fr/tv/14-france.4/14-france.4.php | grep -oP "source:\s*'\K[^']+(?=',)")
          curl_output2=$(curl -e "http://www.callofliberty.fr/" -A "Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" $curl_output)
          echo "$curl_output2" > fr/videof4.m3u8  # Use single > to overwrite existing content   

      - name: Run Script and Generate M3U8 for F5
        run: |
          curl_output=$(curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" http://www.callofliberty.fr/tv/5-france.5/5-france.5.php | grep -oP "source:\s*'\K[^']+(?=',)")
          curl_output2=$(curl -e "http://www.callofliberty.fr/" -A "Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" $curl_output)
          echo "$curl_output2" > fr/videof5.m3u8  # Use single > to overwrite existing content

      - name: Extraire les modifications de la télécommande
        run: git pull origin main          

      - name: Valider et envoyer les modifications
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add fr/videof2.m3u8 fr/videof3.m3u8 fr/videof4.m3u8 fr/videof5.m3u8
          git commit -m "Dernières mises à jour"
          git push
