name: calo

on:
  schedule:
    - cron: '0 */3 * * *'  # Actualise toutes les 3 heures
  workflow_dispatch:      # Activer le déclenchement manuel

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Référentiel d’extraction
        uses: actions/checkout@v4

      - name: Créer un dossier fr
        run: mkdir -p fr

      - name: Créer un dossier txt
        run: mkdir -p txt        

      - name: Exécuter le script et générer M3U8 pour TF1
        run: |
          curl_output=$(curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" http://www.callofliberty.fr/tv/1-TF1/1-TF1.php | grep -oP "source:\s*'\K[^']+(?=',)")
          curl_output2=$(curl -e "http://www.callofliberty.fr/" -A "Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" $curl_output)
          echo "$curl_output2" > fr/videotf1.m3u8  # Utiliser un > unique pour écraser le contenu existant

      - name: Run Script and Generate M3U8 for VideoTF1FS
        run: |
          curl_output=$(curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" http://www.callofliberty.fr/tv/20-TF1SERIESFILMS/20-TF1SERIESFILMS.php | grep -oP "source:\s*'\K[^']+(?=',)")
          curl_output2=$(curl -e "http://www.callofliberty.fr/" -A "Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" $curl_output)
          echo "$curl_output2" > fr/videotf1fs.m3u8  # Use single > to overwrite existing content

      - name: Run Script and Generate M3U8 for VideoTMC
        run: |
          curl_output=$(curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" http://www.callofliberty.fr/tv/10-TMC/10-TMC.php | grep -oP "source:\s*'\K[^']+(?=',)")
          curl_output2=$(curl -e "http://www.callofliberty.fr/" -A "Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" $curl_output)
          echo "$curl_output2" > fr/videotmc.m3u8  # Use single > to overwrite existing content

      - name: Run Script and Generate M3U8 for VideoTFX
        run: |
          curl_output=$(curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" http://www.callofliberty.fr/tv/11-TFX/11-TFX.php | grep -oP "source:\s*'\K[^']+(?=',)")
          curl_output2=$(curl -e "http://www.callofliberty.fr/" -A "Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" $curl_output)
          echo "$curl_output2" > fr/videotfx.m3u8  # Use single > to overwrite existing content

      - name: Run Script and Generate M3U8 for VideoCP
        run: |
          curl_output=$(curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" http://www.callofliberty.fr/tv/4-CANALPLUS/4-CANALPLUS.php | grep -oP "source:\s*'\K[^']+(?=',)")
          curl_output2=$(curl -e "http://www.callofliberty.fr/" -A "Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" $curl_output)
          echo "$curl_output2" > fr/videocp.m3u8  # Use single > to overwrite existing content 

      - name: Run Script and Generate M3U8 for VideoW9
        run: |
          curl_output=$(curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" http://www.callofliberty.fr/tv/9-W9/9-W9.php | grep -oP "source:\s*'\K[^']+(?=',)")
          curl_output2=$(curl -e "http://www.callofliberty.fr/" -A "Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" $curl_output)
          echo "$curl_output2" > fr/videow9.m3u8  # Use single > to overwrite existing content           

      - name: Run Script and Generate M3U8 for Video6ter
        run: |
          curl_output=$(curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" http://www.callofliberty.fr/tv/22-6ter/22-6ter.php | grep -oP "source:\s*'\K[^']+(?=',)")
          curl_output2=$(curl -e "http://www.callofliberty.fr/" -A "Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" $curl_output)
          echo "$curl_output2" > fr/video6ter.m3u8  # Use single > to overwrite existing content   

# curl est un outil permettant de transférer des données depuis ou vers un serveur à l’aide d’URL.
# Il prend en charge ces protocoles : DICT, FILE, FTP, FTPS, GOPHER, GOPHERS, HTTP, HTTPS, IMAP, IMAPS, LDAP, LDAPS,
# MQTT, POP3, POP3S, RTMP, RTMPS, RTSP, SCP, SFTP, SMB, SMBS, SMTP, SMTPS, TELNET, TFTP, WS et WSS.




      - name: Run Script and Generate M3U8 for F2
        run: |
          curl_output=$(curl -s -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0" http://www.callofliberty.fr/tv/2-france.2/2-france.2.php | grep -oP "source:\s*'\K[^']+(?=',)")
          curl_output2=$(curl -e "http://www.callofliberty.fr/" -A "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0" $curl_output)
          echo "$curl_output2" > fr/videof2.m3u8  # Use single > to overwrite existing content   

      - name: Run Script and Generate M3U8 for F3
        run: |
          curl_output=$(curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" http://www.callofliberty.fr/tv/3-france.3/3-france.3.php | grep -oP "source:\s*'\K[^']+(?=',)")
          curl_output2=$(curl -e "http://www.callofliberty.fr/" -A "Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" $curl_output)
          echo "$curl_output2" > fr/videof3.m3u8  # Use single > to overwrite existing content   

      - name: Run Script and Generate M3U8 for F4
        run: |
          curl_output=$(curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" http://www.callofliberty.fr/tv/14-france.4/14-france.4.php | grep -oP "source:\s*'\K[^']+(?=',)")
          curl_output2=$(curl -e "http://www.callofliberty.fr/" -A "Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" $curl_output)
          echo "$curl_output2" > fr/videof4.m3u8  # Use single > to overwrite existing content   

      - name: Run Script and Generate M3U8 for F5
        run: |
          curl_output=$(curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" http://www.callofliberty.fr/tv/5-france.5/5-france.5.php | grep -oP "source:\s*'\K[^']+(?=',)")
          curl_output2=$(curl -e "http://www.callofliberty.fr/" -A "Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" $curl_output)
          echo "$curl_output2" > fr/videof5.m3u8  # Use single > to overwrite existing content

      - name: Extraire les modifications de la télécommande
        run: git pull origin main          

      - name: Valider et envoyer des modifications
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add fr/videotf1.m3u8 fr/videotf1fs.m3u8 fr/videotmc.m3u8 fr/videotfx.m3u8 fr/videocp.m3u8 fr/videow9.m3u8 fr/video6ter.m3u8 fr/videof2.m3u8 fr/videof3.m3u8 fr/videof4.m3u8 fr/videof5.m3u8
          git commit -m "Dernières mises à jour"
          git push
