name: calo

on:
  #schedule:
    #- cron: '0 */3 * * *'  # Actualise toutes les 3 heures
  workflow_dispatch:       # Permet le déclenchement manuel

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Référentiel d’extraction
        uses: actions/checkout@v4

      - name: Créer un dossier fr
        run: mkdir -p fr

      # https://fr.linux-console.net/?p=3665  https://linux.die.net/man/1/curl   
      # https://www.ionos.fr/digitalguide/serveur/configuration/commande-sed-de-linux/
      # tr > https://fr.linux-console.net/?p=30376

      # curl est un outil de transfert de données en ligne de commandes et terminal.
      # Il prend en charge les protocoles pris en charge (DICT, FILE, FTP, FTPS, GOPHER, HTTP, HTTPS, IMAP,
      # IMAPS, LDAP, LDAPS, POP3, POP3S, RTMP, RTSP, SCP, SFTP, SMB, SMBS, SMTP, SMTPS, TELNET et TFTP).

      # user-agent ou -A indique un agent utilisateur.
      # -s silencieux, pas de sortie.
      # -H Transmettre un en-tête personnalisé au serveur.
      # -o dans grep ne correspond qu’à - seule la chaîne correspondante sera affichée.
      # -P regex
      # -e URL de référence.
# echo tr -d 'http://s2.callofliberty.fr/HLS-AES/' > fr/videof5.m3u8


# | yq e '.url' # yq JSON est un sous-ensemble de YAML
# | fx .delivery.url
# | jshon -e url
# | getJsonVal "['delivery']['url'][0]"

      - name: Run Script and Generate M3U8 for lci
        run: |
          base=$(curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" https://mediainfo.tf1.fr/mediainfocombo/L_LCI?format=hls | jq --raw-output '.delivery.url')
          # jq -r signifie jq --raw-output retire les guillemets de chaîne.
          flux=$(curl -e "https://www.tf1.fr" -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" $base)
          echo "$flux" > fr/lci.m3u8
          #mu=$(echo $base | sed "s/.m3u8//g")
          #mu=$(echo $base | tr -d '.m3u8')
          sed -i "s/index/$mu/g" fr/lci.m3u8
          


      - name: Extraire les modifications de la télécommande
        run: git pull origin main          

      - name: Valider et envoyer les modifications
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          ls -la 
          git commit -m "Dernière actualisation"
          git push
