name: calo

on:
  #schedule:
    #- cron: '0 */3 * * *'  # Actualise toutes les 3 heures
  workflow_dispatch:       # Permet le déclenchement manuel

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Référentiel d’extraction
        uses: actions/checkout@v4

      - name: Créer un dossier fr
        run: mkdir -p fr

      # https://fr.linux-console.net/?p=3665  https://linux.die.net/man/1/curl   
      # https://www.ionos.fr/digitalguide/serveur/configuration/commande-sed-de-linux/
      # tr > https://fr.linux-console.net/?p=30376

      # curl est un outil de transfert de données en ligne de commandes et terminal.
      # Il prend en charge les protocoles pris en charge (DICT, FILE, FTP, FTPS, GOPHER, HTTP, HTTPS, IMAP,
      # IMAPS, LDAP, LDAPS, POP3, POP3S, RTMP, RTSP, SCP, SFTP, SMB, SMBS, SMTP, SMTPS, TELNET et TFTP).

      # user-agent ou -A indique un agent utilisateur.
      # -s silencieux, pas de sortie.
      # -H Transmettre un en-tête personnalisé au serveur.
      # -o dans grep ne correspond qu’à - seule la chaîne correspondante sera affichée.
      # -P regex
      # -e URL de référence.

      - name: Exécuter le script et générer M3U8 pour fr2
        run: |
          base=$(curl -s -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" http://www.callofliberty.fr/tv/2-france.2/2-france.2.php | grep -oP "source:\s*'\K[^']+(?=',)")
          flux=$(curl -e "http://www.callofliberty.fr/" -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" $base)
          #m3u8=$(echo "$flux" tr "http://s2.callofliberty.fr/HLS-AES/https" "https")
          echo "$flux" > fr/videof2.m3u8
          #sed -i 's/http:\/\/s2.callofliberty.fr\/HLS-AES\/https/https/g' fr/videof2.m3u8
          sed -i "s|http://s2.callofliberty.fr/HLS-AES/||g" fr/videof2.m3u8
          #sed -i "s/http:\/\/s2.callofliberty.fr\/HLS-AES\////g" fr/videof2.m3u8


      - name: Construire un flux frinfo
        run: |
          source=$(curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" https://hdfauth.ftven.fr/esi/TA?url=https://simulcast-p.ftven.fr/simulcast/France_Info/hls_monde_frinfo/index.m3u8)
          base=$(curl -e "https://www.france.tv/" -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" | grep -oP "index[^\n\r]*" "$source")
          echo "$base" > fr/frinfo.m3u8

#token = "https://hdfauth.ftven.fr/esi/TA?url="
      #  source = s.get(token + url).text
      #  base = s.get(source).text
      #  pat = re.compile("index[^\n\r]*")
       # res = re.sub(pat,"",source)
      #  m3u8 = base.replace("France", (res + "France"))

      - name: Run Python Script M6
        run: |
         python_output=$(curl -X GET -i -v -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" https://www.livehdtv.net/token.php?stream=m6 | grep -oP 'file:\s*"([^"]+\.m3u8[^"]*)"')
         curl_output2=$(curl -e "https://www.livehdtv.net" -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" "$python_output")
         curl_output3=$(echo "$curl_output2" | sed 's|tracks-|https://livetvde.net/m6/tracks-|g')
         echo "$curl_output3" > fr/m6.m3u8  # Use single > to overwrite existing content



# | yq e '.url' # yq JSON est un sous-ensemble de YAML
# | fx .delivery.url
# | jshon -e url
# | getJsonVal "['delivery']['url'][0]"

      - name: Run Script and Generate M3U8 for lci
        run: |
          base=$(curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" https://mediainfo.tf1.fr/mediainfocombo/L_LCI?format=hls.json | jq --raw-output '.delivery.url')
# jq -r signifie jq --raw-output retire les guillemets de chaîne.
          flux=$(curl -i $base)
          echo "$flux" > fr/lci.m3u8

      - name: Run Script and Generate M3U8 for F5
        run: |
          curl_output=$(curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" http://www.callofliberty.fr/tv/5-france.5/5-france.5.php | grep -oP "source:\s*'\K[^']+(?=',)")
          curl_output2=$(curl -e "http://www.callofliberty.fr/" -A "Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" $curl_output)
          echo "$curl_output2" > fr/videof5.m3u8  # Use single > to overwrite
          echo fr/videof5.m3u8 | tr -d 'http://s2.callofliberty.fr/HLS-AES/'

      - name: Extraire les modifications de la télécommande
        run: git pull origin main          

      - name: Valider et envoyer les modifications
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          ls -la 
          git commit -m "Dernière actualisation"
          git push
