name: calo

on:
  #schedule:
    #- cron: '0 */3 * * *'  # Actualise toutes les 3 heures
  workflow_dispatch:       # Permet le déclenchement manuel

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Référentiel d’extraction
        uses: actions/checkout@v4

      - name: Créer un dossier fr
        run: mkdir -p fr

      # https://fr.linux-console.net/?p=3665  https://linux.die.net/man/1/curl   
      # https://www.ionos.fr/digitalguide/serveur/configuration/commande-sed-de-linux/
      # tr > https://fr.linux-console.net/?p=30376

      - name: Exécuter le script et générer M3U8 pour fr2
        run: |
          base=$(curl -s -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" http://www.callofliberty.fr/tv/2-france.2/2-france.2.php | grep -oP "source:\s*'\K[^']+(?=',)")
          flux=$(curl -e "http://www.callofliberty.fr/" -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" $base)
          echo "$flux" > fr/videof2.m3u8
          #  ("s/ /_/g") indique à sed de se comporter de façon globale ("récursive").
          # Vous devez échapper les caractères spéciaux avec \.
          # L’option pour mettre à jour le fichier en place est -i.
          sed -i 's/http:\/\/s2.callofliberty.fr\/HLS-AES\/https/https/g' fr/videof2.m3u8

          
    # - name: générer M3U8 pour fr2
      #  run: |
       #   sed -i 's/http:\/\/s2.callofliberty.fr\/HLS-AES\/https/https/g' fr/videof2.m3u8 # marche aussi

      - name: Run Script and Generate M3U8 for F3
        run: |
          curl_output=$(curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" http://www.callofliberty.fr/tv/3-france.3/3-france.3.php | grep -oP "source:\s*'\K[^']+(?=',)")
          curl_output2=$(curl -e "http://www.callofliberty.fr/" -A "Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" $curl_output)
          echo "$curl_output2" > fr/videof3.m3u8  # Use single > to overwrite existing content   
          sed -i "s|http://s2.callofliberty.fr/HLS-AES/||g" fr/videof3.m3u8

      - name: Run Script and Generate M3U8 for F4
        run: |
          curl_output=$(curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" http://www.callofliberty.fr/tv/14-france.4/14-france.4.php | grep -oP "source:\s*'\K[^']+(?=',)")
          curl_output2=$(curl -e "http://www.callofliberty.fr/" -A "Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" $curl_output)
          echo "$curl_output2" > fr/videof4.m3u8  # Use single > to overwrite 
          sed -i "s|http://s2.callofliberty.fr/HLS-AES/||g" fr/videof4.m3u8

      - name: Run Script and Generate M3U8 for F5
        run: |
          curl_output=$(curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" http://www.callofliberty.fr/tv/5-france.5/5-france.5.php | grep -oP "source:\s*'\K[^']+(?=',)")
          curl_output2=$(curl -e "http://www.callofliberty.fr/" -A "Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" $curl_output)
          echo "$curl_output2" > fr/videof5.m3u8  # Use single > to overwrite
          sed -i 's/http:\/\/s2.callofliberty.fr\/HLS-AES\/https/https/g' fr/videof5.m3u8      

      - name: Extraire les modifications de la télécommande
        run: git pull origin main          

      - name: Valider et envoyer les modifications
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add fr/videof2.m3u8 fr/videof3.m3u8 fr/videof4.m3u8 fr/videof5.m3u8
          git commit -m "Dernière actualisation"
          git push
