name: epg
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest



    steps:
      -  uses: actions/checkout@v4
      # Installer Node.js => https://github.com/actions/setup-node
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

# https://github.com/iptv-org/epg
      - name: Générer les fichiers
        run: |
          npm install
          npm run start
          # Vous devrez également installer "git" avec la commande suivante :
          git clone --depth 1 -b master https://github.com/iptv-org/epg.git
          # Accédez ensuite au dossier epg téléchargé :
          cd epg
          # Et installez toutes les dépendances :
          npm install
          # Pour lancer le téléchargement du guide, sélectionnez l’un des sites pris en charge et collez son nom dans la commande ci-dessous
          # Et une fois le téléchargement terminé, le guide sera enregistré dans le fichier guide.xml.
          npm run grab -- --channels=../bin/channels.xml --output=../bin/guide.xml
          cd ..
          rm -rf epg

      - name: Commit and push
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes"
          else
            git config --global user.name github-actions
            git config --global user.email github-actions@github.com
            git add bin/*
            git commit -m "Mise à jour de la liste de lecture et de l’EPG"
            git push
          fi
