name: run frinfo.py

on:
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday


  workflow_dispatch:

permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
     matrix:
      python-version: ["3.10"]

    steps:
      

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run frinfo.py
        run: python frinfo.py

      #- name: updating frinfo
        #run: sh ${GITHUB_WORKSPACE}/sources/frinfo.py
        
          
      - name: config
      # Pour pouvoir travailler sur un projet,
      # vous avez besoin d’un nom d’utilisateur et d’une adresse email associée valide.
      # Informer Git que vous voulez inclure les mises à jour dans un fichier.
        run: |
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
         git add -A 
          ls -la 
    
           
      - name: commit & push
        run: |
          git commit -am "Actualisation du flux"
          git push
      
