name: frtest


on:
 # schedule:
  #  - cron: '0 0/3 * * *'

  workflow_dispatch:
    inputs:
     VPN_USER: 
     description: 'username'
     required: true
     default: ''
    VPN_PASS:
     description: 'password'
     required: true
     default: ''
    VPN_CONFIG_FILE_PATH:
     description: '${GITHUB_WORKSPACE}/tunnel/client.ovpn'
     required: true
     default: '${GITHUB_WORKSPACE}/tunnel/client.ovpn'


permissions:
  contents: write


     

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
     
     - name: checkout
       uses: actions/checkout@v3
 
     - name: config
      # Pour pouvoir travailler sur un projet,
      # vous avez besoin d’un nom d’utilisateur et d’une adresse email associée valide. 
       run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      
      
     - name: updating frinfo
       run: |
        sudo apt-get install openvpn -y
        shell: bash
       
     - name: updating fri
       run: |
        echo -e "${{ inputs.VPN_USER }}\n${{ inputs.VPN_PASS }}" > ~/.vpncreds
        sudo openvpn --config "${{inputs.VPN_CONFIG_FILE_PATH}}" --auth-user-pass ~/.vpncreds --daemon
        # Il y a un temps de veille supplémentaire de 10 secondes à la fin de cette action.
        sleep 10s
       shell: bash
        
     - name: git add
      # Informer Git que vous voulez inclure les mises à jour dans un fichier.
       run: |
          git add -A
          ls -la 
          
     - name: commit & push
       run: |
          git commit -am "Actualisation du flux"
          git push
          
          
