name: lci refrech
on:
  schedule:
    - cron: "08 */3 * * *"
    
  workflow_dispatch:

jobs:
  update-stream:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v3

      - name: updating lci
        run: sh sources/lci.sh

      - name: setup git config
        run: |
          git config user.name "lci bot"
          git config user.email "<>"
      - name: commit
        run: |
          git pull
          git commit -m "lci updated"
          git push origin master
