name: lci refrech
on:
  schedule:
    - cron: "02 */3 * * *"
    
  workflow_dispatch:

jobs:
  update-stream:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v3

      - name: updating lci
        run: sh sources/lci.sh

      - name: commit
        run: |
          git add lci.m3u8
          git commit --amend
          
