name: lci refrech
on:
  #schedule:
    #- cron: "02 */3 * * *"
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      
      - name: Main
        run: |
          pwd
          chmod +x sh ${GITHUB_WORKSPACE}/sources/lci.sh
          sh ${GITHUB_WORKSPACE}/sources/lci.sh
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "links are updated"
          git push
      
  
