name: 'VPNConnect'
        workflow_dispatch:
  schedule:
    - cron: '0 0/2 * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest

inputs:
  VPN_USER:
    description: 'username'
    required: true
    default: ''
  VPN_PASS:
    description: 'password'
    required: true
    default: ''
  VPN_CONFIG_FILE_PATH:
    description: 'Le chemin d’accès à votre fichier de configuration openvpn'
    required: true
    default: '${GITHUB_WORKSPACE}/tunnel/client.ovpn'
runs:
  using: 'composite'
  steps:
    - run: |
        sudo apt-get install openvpn -y
      shell: bash
    - run: |
        echo -e "${{ inputs.VPN_USER }}\n${{ inputs.VPN_PASS }}" > ~/.vpncreds
        sudo openvpn --config "${{inputs.VPN_CONFIG_FILE_PATH}}" --auth-user-pass ~/.vpncreds --daemon
        # Il y a un temps de veille supplémentaire de 10 secondes à la fin de cette action.
        sleep 10s
      shell: bash
