name: rakuten
# Actualisation du flux.
on:
  schedule:
    - cron: "0 */12 * * *"
    
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v3

      - name: config
      # Pour pouvoir travailler sur un projet,
      # vous avez besoin d’un nom d’utilisateur et d’une adresse email associée valide. 
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      
      - name: Actualisation de la liste
        run: python raku/main.py > raku/rakutenfr.m3u8

        env:
          HTTP_PROXY: http://${{ secrets.PROXY_USERNAME }}:${{ secrets.PROXY_PASSWORD }}@${{ secrets.PROXY_IP }}:5009
          HTTPS_PROXY: http://${{ secrets.PROXY_USERNAME }}:${{ secrets.PROXY_PASSWORD }}@${{ secrets.PROXY_IP }}:5009
        
      - name: git add
      # Informer Git que vous voulez inclure les mises à jour dans un fichier.
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -am "Actualisation des flux"
          git push





