name: recup


on:
# L’événement schedule permet de déclencher un workflow à une heure planifiée.
  schedule:
# 30 */4 signifie que la commande sera lancée toutes les 4 heures á la 6 ème minute.
    - cron:  '30 */4 * * *'

   # Vous permet d'exécuter ce workflow manuellement à partir de l'onglet Actions.
  workflow_dispatch:

jobs:
  build:
  
   runs-on: ubuntu-latest
   strategy:
     matrix:
      python-version: ["3.10"]

   steps:
      
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
         python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install ruff pytest
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with ruff
        run: |
           # arrêter la construction s'il y a des erreurs de syntaxe Python ou des noms non définis
           ruff --format=github --select=E9,F63,F7,F82 --target-version=py310 .
           # ensemble de règles de ruff par défaut avec les annotations GitHub
           ruff --format=github --target-version=py310 .
      - name: Test with pytest
        run: |
         pytest

   
      - name: actualisation execute
        run: |
         ./sources/execute.py




