name: XMLTV

on:
  #schedule:
    #- cron: '18 */4 * * *'  # Actualise toutes les 4 heures
  workflow_dispatch:       # Permet le déclenchement manuel

jobs:
  creer-xml:
    runs-on: ubuntu-latest

    steps:
      - name: Référentiel d’extraction
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}

      - name: Installe la version de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8' #python-version: '3.10'
          cache: 'pip' # Mise en cache des dépendances pip
      - run: pip install -r requirements.txt # Spécifiez les versions exactes des dépendances dans le fichier requirements.txt.
      
      - name: Configure grabber
        run: |-
          rm -f tv_grab_fr_teleloisirs.conf
          for id in $XMLTV_IDS; do
              echo "channel=$id.api-tel.programme-tv.net" >>tv_grab_fr_teleloisirs.conf
          done
        env:
          XMLTV_IDS: 147 156 192 195
      - name: Run grabber
        run: python tv_grab_fr_teleloisirs.py --config-file tv_grab_fr_teleloisirs.conf --days 1 --output xmltv_teleloisirs.xml
        env:
          TZ: Europe/Paris
      - name: Upload XMLTV file
        uses: actions/upload-artifact@v4
        with:
          name: xmltv
          path: xmltv_teleloisirs.xml
           echo gzip -c xmltv_teleloisirs.xml > xmltv_teleloisirs.xml.gz
          

      - name: Add XMLTV file to repository
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add xmltv_teleloisirs.xml
          git commit -m "$(date)"
