name: yt
on:
 # schedule:
  #  - cron: '0 */3 * * *' #Configuré pour l’obtenir automatiquement toutes les 3 heures

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp
        
#    - name: Install youtube-dl
  #    run: |
   #     sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
#        sudo chmod a+rx /usr/local/bin/youtube-dl







    - name: essai1
      run: |
        touch ./essai1.m3u8
        sudo cat >./essai1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://tv-programme.com/c8/direct)
        EOL
        
#    - name: CNN_News18
  #    run: |
 #       touch ./CNN_News18.m3u8
   #     sudo cat >./CNN_News18.m3u8 <<EOL
   #     #EXTM3U
      #  #EXT-X-VERSION:3
    #    #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
    #    $(youtube-dl -g https://www.youtube.com/c/CtsTw/live)
    #    EOL

    - name: Marche de Tokyo 24/7
      run: |
        touch ./tokyo.m3u8
        sudo cat >./tokyo.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=cH7VBI4QQzA&pp=ygUETGl2ZQ%3D%3D)
        EOL     



    - name: git add
      run: |
        git add -A
        ls -la

    - name: commit & push
      run: |
        git commit -m "Les liens sont mis à jour"
        git push
